#!/usr/bin/env bash

FROM_FILE=$1
USERNAME=$3
SSH_KEY=$4
IP=$2
if [ $# -ne 4 ]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -r -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FROM_FILE" "$USERNAME@$IP:~/"
