#!/usr/bin/env bash

# read argument from cli
FROM_FILE=$1
USERNAME=$3
SSH_KEY=$4
IP=$2

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FROM_FILE" "$USERNAME@$IP":~
fi
