#!/usr/bin/env bash

# Update the package index
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
sudo service nginx restart
