#!/usr/bin/env bash

# Update the package index
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
cat <<EOF > /ect/nginx/sites-available/default
server {
        listen 80;
        listen [::]:80;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location / {
                return 200 'Hello world!';
        }
}
EOF

# Restart Nginx without using systemctl
sudo service nginx restart
