#!/usr/bin/env bash

# Update the package index
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
cat <<EOF > /var/www/html/index.nginx-debian.html
Hello World!
EOF

# Restart Nginx without using systemctl
sudo service nginx restart
