#!/usr/bin/env bash
# Install nginx on my webserver

sudo apt-get update -y
sudo apt-get install -y nginx

cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80;
	listen [::]:80;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	location / {
		return 200 'Hello World!';
	}

        rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
EOF

sudo service nginx restart
