#!/usr/bin/env bash
# script to create RSA key pair

# Key variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generating RSA key pair
ssh-keygen -t rsa -b ${KEY_BITS} -f "${KEY_NAME}" -N  "${PASSPHRASE}"
